export const GameEventType = Object.freeze({
	CHAT_MESSAGE: "CHAT_MESSAGE",
	USER_DRAW: "USER_DRAW",
	MOUSE_UP: "MOUSE_UP",
	ROUND_NOTIFICATION: 'ROUND_NOTIFICATION',
	JOIN_GAME: 'JOIN_GAME',
	GAME_OVER: 'GAME_OVER'
});
